# _config.yml - MarkOWiHu Photographer main web pages Site Configuration • MarkOWiHu Fotógrafo Alicante
# Updated: 09/09/2026 - Enabled jekyll-sitemap plugin for automated sitemap.xml generation

url: "https://markowihu.es"

plugins:
  - jekyll-sitemap